coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 2%
        if_no_uploads: error
    patch:
      default:
        target: 80%
        threshold: 5%
        if_no_uploads: error

comment:
  layout: 'reach,diff,flags,tree,reach'
  behavior: default

ignore:
  - 'tests/'
  - 'scripts/'
  - 'benchmarks/'
  - 'examples/'
  - 'temp/'
  - '**/*.test.ts'
  - '**/*.config.*'
  - '**/test-utils.ts'

github_checks:
  annotations: false
