name: Update Changelog

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Generate Changelog
        run: |
          # Get the latest tag
          LATEST_TAG=$(git describe --tags --abbrev=0)
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 ${LATEST_TAG}^ 2>/dev/null || echo "")

          echo "Generating changelog for ${LATEST_TAG}"

          # Generate changelog entry
          if [ -n "$PREVIOUS_TAG" ]; then
            echo "Changes from ${PREVIOUS_TAG} to ${LATEST_TAG}"
            git log ${PREVIOUS_TAG}..${LATEST_TAG} --pretty=format:"- %s (%h)" --no-merges
          else
            echo "Initial release ${LATEST_TAG}"
            git log ${LATEST_TAG} --pretty=format:"- %s (%h)" --no-merges
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: update changelog for release"
          title: "docs: update changelog for release"
          body: |
            This PR updates the changelog with the latest release information.

            Auto-generated by the changelog workflow.
          branch: update-changelog-${{ github.run_number }}
          delete-branch: true
